function out = multi_objective(paras, Ft_1, P1_exp_1, time_1,...
                             Ft_2, P1_exp_2, time_2,...
                             Ft_3, P1_exp_3, time_3,...
                             Ft_4, P1_exp_4, time_4,...
                             Ft_5, P1_exp_5, time_5,...
                             num_eq, num_neq, num_rel)
[mu_eq, alpha_eq, eta_list, mu_neq, alpha_neq] = paras_to_array(paras, num_eq, num_neq, num_rel);

P1_list_1 = get_P1_list(mu_eq, alpha_eq, mu_neq, alpha_neq, eta_list, Ft_1, time_1);
P1_list_2 = get_P1_list(mu_eq, alpha_eq, mu_neq, alpha_neq, eta_list, Ft_2, time_2);
P1_list_3 = get_P1_list(mu_eq, alpha_eq, mu_neq, alpha_neq, eta_list, Ft_3, time_3);
P1_list_4 = get_P1_list(mu_eq, alpha_eq, mu_neq, alpha_neq, eta_list, Ft_4, time_4);
P1_list_5 = get_P1_list(mu_eq, alpha_eq, mu_neq, alpha_neq, eta_list, Ft_5, time_5);

out = [P1_exp_1-P1_list_1, P1_exp_2-P1_list_2, P1_exp_3-P1_list_3, P1_exp_4-P1_list_4, P1_exp_5-P1_list_5];
end