function out = get_tau_iso_eig_val(xi_neq, I1, lambda)
out = dPsi_dlambda_neq(xi_neq, I1, lambda) * lambda...
      - dPsi_dlambda_neq(xi_neq, I1, lambda) * lambda / 3.0...
      - dPsi_dlambda_neq(xi_neq, I1, lambda) * lambda / 3.0;
end